# Shared aliases. Sourced by zsh and bash.

alias c='clear'
alias nf='fastfetch'
alias pf='fastfetch'
alias ff='fastfetch'
alias ls='eza -a --icons=always'
alias ll='eza -al --icons=always'
alias lt='eza -a --tree --level=1 --icons=always'
alias shutdown='systemctl poweroff'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias e='msedit'
alias wifi='nmtui'
alias gradlew='nice -n 15 ionice -c 3 ./gradlew'
alias reset='echo -e "\e[3J" && reset'
alias lg='lazygit'
alias y='yazi'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
